version: '3.8'

services:
  backend:
    build: ./tactical-eye-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./tactical-eye-backend:/app  
      - /app/node_modules 
